version: '3'

services:
  api:
    container_name: api.ahmadkaisar.dev
    build:
      context: .
      dockerfile: docker/Dockerfile.golang
    environment:
      - ACCESS_CONTROL_ALLOW_ORIGIN=*
      - PORT=5000
      - JWT_SIGN_KEY=somethinginterestinghere123456
      - MYSQL_HOST=database
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=ahmadkaisardev
    ports:
      - 5000:5000
    tty: true
    command: ahmadkaisardev
    restart: always
    healthcheck:
      test: curl --fail http://localhost:5000/ || exit 1
      interval: 60s
      retries: 2
      start_period: 30s
      timeout: 5s
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 512M
        reservations:
          cpus: '0.05'
          memory: 128M
    volumes:
      - ./files:/go/bin/files:z
    depends_on:
      - database
  database:
    container_name: db.ahmadkaisar.dev
    build: 
      context: .
      dockerfile: docker/Dockerfile.mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 13306:3306
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 1G
        reservations:
          cpus: '0.1'
          memory: 256M
    volumes:
      - ./mysql:/var/lib/mysql:z
    tty: true